/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HarvestsRouteImport } from './routes/harvests'
import { Route as IndexRouteImport } from './routes/index'

const HarvestsRoute = HarvestsRouteImport.update({
  id: '/harvests',
  path: '/harvests',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/harvests': typeof HarvestsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/harvests': typeof HarvestsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/harvests': typeof HarvestsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/harvests'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/harvests'
  id: '__root__' | '/' | '/harvests'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HarvestsRoute: typeof HarvestsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/harvests': {
      id: '/harvests'
      path: '/harvests'
      fullPath: '/harvests'
      preLoaderRoute: typeof HarvestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HarvestsRoute: HarvestsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
